name: pratiksha
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_image_compress: ^1.0.0
  flutter_dotenv: ^5.0.2


  # Firebase dependencies
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.4.4
  intl: ^0.18.0

  # Local storage
  shared_preferences: ^2.1.0

  # File and image handling
  dropbox_client: ^1.0.0
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  open_file: ^3.2.1


  # UI and widgets
  syncfusion_flutter_datagrid: ^27.1.51
  carousel_slider: ^5.0.0
  fl_chart: ^0.69.2

  # Mapping and geolocation
  flutter_map: ^7.0.2
  flutter_heatmap_calendar: ^1.0.5
  latlong2: ^0.9.1

  # WebView
  webview_flutter: ^4.9.0
  flutter_web_auth: ^0.6.0

  # SQLite for local databases
  sqflite: ^2.4.0

  # Path utilities
  path: ^1.8.0
  path_provider: ^2.0.5

  # HTTP requests
  http: ^1.2.1
  url_launcher: ^6.1.7
  uni_links: ^0.5.1
  flutter_secure_storage: ^8.0.0

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env

  # Uncomment and add your asset files here:
  # assets:
  #   - images/your_image.png

  # Uncomment and define custom fonts here:
  # fonts:
  #   - family: YourFontFamily
  #     fonts:
  #       - asset: fonts/YourFontFile.ttf
